trying to debug failure to 78_deploy_docs
ERROR   -  Failed to deploy to GitHub with error:
To https://github.com/nestauk/ds-cookiecutter
 ! [rejected]        gh-pages -> gh-pages (fetch first)
error: failed to push some refs to 'https://github.com/nestauk/ds-cookiecutter'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
...